### ISSUE TITLE
Oracles repo is unable to build with any (http = 1) version

### ISSUE THREAD

**Issue by kurotych** [helium/oracles#670]
In [Cargo.toml](https://github.com/helium/oracles/blob/main/Cargo.toml) http version is specified as "any".
But a few hours ago the "http" crate with version "1" was released and "oracles" seems doesn't able to be compiled with it.

Please specify a more strict version (0.2.11 I think) or make the current repo compatible with http v1

### STR
Change `http = "*"` to `http = "1"` in Cargo.toml and try to build
![image](https://github.com/helium/oracles/assets/20345096/b880daf7-6009-4b06-ae4c-7115e4173cdf)

### Workaround 
```toml
[patch.crates-io]
http = { git = "https://github.com/hyperium/http", tag = "v0.2.11" }
```
